server:
  port: 8083

spring:
  jpa:
    hibernate.ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    generate-ddl: true
  datasource:
    url: jdbc:mysql://localhost:3306/movie_app
    username: movie-admin
    password: admin
